name: Deploy Azure Function

on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'GenerateSonnet/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'GenerateSonnet'   # set this to your function app name on Azure
  POM_XML_DIRECTORY: '.'                    # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17'                         # set this to the java version to use (e.g. '8', '11', '17')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        run: mvn -f GenerateSonnet/pom.xml clean package

      - name: check jar
        run: tree GenerateSonnet/target/azure-functions/

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: 'GenerateSonnet/target/azure-functions/func-sonnet-generator/*.jar'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-pom-xml: true