name: Deploy Azure Function

on:
  push:
    branches:
      - main
    paths:
      - 'GenerateSonnet/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -f GenerateSonnet/pom.xml clean package

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'GenerateSonnet'
          package: 'GenerateSonnet/target/*.jar'
          publish-profile: 'preview'